function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 06-Oct-2022 22:49:46

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1);

% Create ylabel
ylabel('{y}');

% Create xlabel
xlabel('{x}');

% Create title
title('{x}^{2} + {y}^{2}');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 2]);
view(axes1,[24.6 4.76321167883212]);
grid(axes1,'on');
hold(axes1,'off');
