#!/bin/sh


pdf2ps "area f(x)=x e g(x)=x^2.pdf"
pdf2ps "asintoto orizzontale.pdf"
pdf2ps "asintoto verticale.pdf"
pdf2ps "compressione e dilatazione in direzione orizzontale.pdf"
pdf2ps "contrazione e dilatazione in direzione verticale.pdf"
pdf2ps "esempio di limite di una funzione.pdf"
pdf2ps "esempio limite di funzione.pdf"
pdf2ps "esempio punto angoloso.pdf"
pdf2ps "esempio punto cuspide.pdf"
pdf2ps "esempio studio di funzione 2.pdf"
pdf2ps "esercizio d'esempio di uno strudio di funzione.pdf"
pdf2ps "esercizio retta tangente 1.pdf"
pdf2ps "funzione arccos.pdf"
pdf2ps "funzione arcsin.pdf"
pdf2ps "funzione arctg.pdf"
pdf2ps "funzione cos.pdf"
pdf2ps "funzione ctg.pdf"
pdf2ps "funzione lineare.pdf"
pdf2ps "funzione logaritmica.pdf"
pdf2ps "funzione potenziale fratta.pdf"
pdf2ps "funzione potenziale x^a.pdf"
pdf2ps "funzione potenziale x^n.pdf"
pdf2ps "funzione sin.pdf"
pdf2ps "funzione tg.pdf"
pdf2ps "funzione valore assoluto.pdf"
pdf2ps "funzioni trigonometriche.pdf"
pdf2ps "grafico dimostrativo di lagrange.pdf"
pdf2ps "insiemi funzioni composte.pdf"
pdf2ps "le coniche circonferenze.pdf"
pdf2ps "le coniche ellisse.pdf"
pdf2ps "le coniche iperbole equilattera.pdf"
pdf2ps "le coniche iperbole.pdf"
pdf2ps "le coniche parabola.pdf"
pdf2ps "legge di rolle immagine 1.pdf"
pdf2ps "operazione sul grafico traslazione della asse x.pdf"
pdf2ps "operazione sul grafico traslazione della asse y.pdf"
pdf2ps "ordine di infiniti.pdf"
pdf2ps "y=_lnx_.pdf"
